### PR TITLE
Replace rustc commit hash/date when not present

### LINKED ISSUE #78: Rustc commit date and hash does not work when they are unknown
I use vergen in my project [Calypso](https://github.com/calypso-lang/calypso). I recently had a user report to me (though not through GitHub issues) that the build.rs script would not generate the `VERGEN_RUSTC_COMMIT_DATE` and `VERGEN_RUSTC_COMMIT_HASH` environment variables when `rustc -vV` shows them as unknown:
```
$ rustc -vV
rustc 1.51.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

I don't know *why* they are marked as unknown, but they are. It appears that when these are unknown, they are marked as `None` in `rustc_version::VersionMeta::commit_{hash, date}`.
Instead, of being omitted when they are not present, these values should be replaced with another value like "unknown" to prevent this issue from occurring.

### PR DESCRIPTION
**Pull request by ThePuzzlemaker**
Occasionally `rustc -vV` (used by `rustc_version`) will return `unknown`
for the commit date and/or hash. In `rustc_version::VersionMeta`, this
is represented as a `None` value in the `commit_hash` and `commit_date`
fields. This is a problem if these variables are depended on by the
application, as vergen will not panic if they are not present, but will
instead silently omit them.

This PR fixes this issue by replacing a `None` value for a commit hash
or date with the string "unknown".

Fixes #78

### CODE REVIEW

File: src/feature/rustc.rs [hunk 1]
```diff
@@ -150,15 +150,15 @@ pub(crate) fn configure_rustc(instructions: Instructions, config: &mut Config) -
             add_entry(
                 config.cfg_map_mut(),
                 VergenKey::RustcCommitHash,
-                rustc.commit_hash,
+                Some(rustc.commit_hash.unwrap_or("unknown".to_string())),
```
Comment (jasonozias) [inline src/feature/rustc.rs:153]: This is failing the lint checks.   Can you update the `unwrap_or` to `unwrap_or_else(|| "unknown".to_string())`

File: src/feature/rustc.rs [hunk 2]
```diff
@@ -150,15 +150,15 @@ pub(crate) fn configure_rustc(instructions: Instructions, config: &mut Config) -
...
             );
         }
 
         if *rustc_config.commit_date() {
             add_entry(
                 config.cfg_map_mut(),
                 VergenKey::RustcCommitDate,
-                rustc.commit_date,
+                Some(rustc.commit_date.unwrap_or("unknown".to_string())),
```
Comment (jasonozias) [inline src/feature/rustc.rs:161]: Same as above.

**Review by jasonozias — CHANGES_REQUESTED** [review]

File: src/feature/rustc.rs (hunk 1 above)
Comment (ThePuzzlemaker) [reply src/feature/rustc.rs:153]: Woops, sorry, forgot to run clippy :sweat_smile:

**Review by CraZySacX — APPROVED** [review]
